# Default values for nginx-info
replicaCount: 3

image:
  repository: raghavendramallela/podnameuptime
  tag: jammy
  pullPolicy: IfNotPresent
  pullsecret: "regcred"

service:
  # type: NodePort
  type: ClusterIP
  port: 80
  targetPort: 80
  # nodePort: 30069

readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
